### ISSUE TITLE
Search error 500 by searching for content with minus or plus

### ISSUE THREAD

**Issue by leph24** [massiveart-webservices/ZOOLU#170]
Search error 500 by searching for content with minus or plus (only with non breaking space before)

Example:
1. Test - Something
2. Test + Something
3. Test   Something (double spacing)

**Comment by alexander-schranz** [comment]
Error Log:

```
2013-11-18T13:04:48+01:00 ERR (3): exception 'Zend_Search_Lucene_Search_QueryParserException' with message 'It's not allowed to mix boolean and signs styles in the same subquery.' in /usr/share/php/Zend/Search/Lucene/Search/QueryParserContext.php:240
Stack trace:
#0 /usr/share/php/Zend/Search/Lucene/Search/QueryParser.php(534): Zend_Search_Lucene_Search_QueryParserContext->addLogicalOperator(15)
#1 /usr/share/php/Zend/Search/Lucene/FSMAction.php(63): Zend_Search_Lucene_Search_QueryParser->logicalOperator()
#2 /usr/share/php/Zend/Search/Lucene/FSM.php(413): Zend_Search_Lucene_FSMAction->doAction()
#3 /usr/share/php/Zend/Search/Lucene/Search/QueryParser.php(380): Zend_Search_Lucene_FSM->process(15)
#4 /var/data/websites/zoolu.siri.at/library/massiveart/website/search.class.php(103): Zend_Search_Lucene_Search_QueryParser::parse('+(zo_node_summa...', 'UTF-8')
#5 /var/data/websites/zoolu.siri.at/library/massiveart/website/search.class.php(63): Search->searchByPath('/var/data/websi...')
#6 /var/data/websites/zoolu.siri.at/application/website/default/controllers/SearchController.php(101): Search->search()
#7 /usr/share/php/Zend/Controller/Action.php(516): SearchController->indexAction()
#8 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#9 /usr/share/php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/data/websites/zoolu.siri.at/public/index.php(157): Zend_Controller_Front->dispatch()
#11 {main}

Next exception 'Zend_Search_Lucene_Exception' with message 'It's not allowed to mix boolean and signs styles in the same subquery.' in /usr/share/php/Zend/Search/Lucene/Search/QueryParser.php:389
Stack trace:
#0 /var/data/websites/zoolu.siri.at/library/massiveart/website/search.class.php(103): Zend_Search_Lucene_Search_QueryParser::parse('+(zo_node_summa...', 'UTF-8')
#1 /var/data/websites/zoolu.siri.at/library/massiveart/website/search.class.php(63): Search->searchByPath('/var/data/websi...')
#2 /var/data/websites/zoolu.siri.at/application/website/default/controllers/SearchController.php(101): Search->search()
#3 /usr/share/php/Zend/Controller/Action.php(516): SearchController->indexAction()
#4 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /var/data/websites/zoolu.siri.at/public/index.php(157): Zend_Controller_Front->dispatch()
#7 {main}
```
